routes/web.php
<?php

use App\Http\Controllers\Admin\Designs\ConsultationRequestController;
use App\Http\Controllers\Admin\Designs\DesignController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\RoomCategoryController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.index');
});

Route::prefix('admin')
    ->middleware('auth')
    ->name('admin.')->group(function(){
    Route::get('/', [HomeController::class, 'index']);
    Route::resource('users', UserController::class);
    Route::resource('room_categories', RoomCategoryController::class);
    Route::resource('designs',DesignController::class);
    Route::resource('requests',ConsultationRequestController::class);
    Route::resource('images',ImageController::class);
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/layouts/partials/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">Marina construction</a>.</strong>
    All rights reserved.
</footer>

resources/views/admin/layouts/partials/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Marina Admin</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{{asset('assets/admin/css/plugins.css')}}">
    <link rel="stylesheet" href="{{asset('assets/admin/css/app.css')}}">

    {{--  calendar --}}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/base/jquery-ui.css">

</head>

resources/views/admin/layouts/partials/javascripts.blade.php
<script src="{{asset('assets/admin/js/app.js')}}"></script>
<script src="{{asset('assets/admin/js/plugins.js')}}"></script>

<script>
    jQuery(document).ready(function ($) {
        $(".clickable-row").click(function () {
            window.location = $(this).data("href");
        });
    });
</script>

<script type="text/javascript">
    $(function () {
        $('.date-picker').datepicker({
            changeYear: true,
            changeMonth: false,
            showButtonPanel: true,
            dateFormat: 'yy',
            yearRange: 'c-10:c+0',
            onClose: function (dateText, inst) {
                $(this).datepicker('setDate', new Date(inst.selectedYear, 1));
            }
        });
    });
</script>

<!-- upload images  -->
<script>
    $(function () {
        var multiImgPreview = function (input, imgPreviewPlaceholder) {

            if (input.files) {
                var filesAmount = input.files.length;

                for (i = 0; i < filesAmount; i++) {
                    var reader = new FileReader();

                    reader.onload = function (event) {
                        $($.parseHTML('<img>')).attr('src', event.target.result).appendTo(imgPreviewPlaceholder);
                    }
                    reader.readAsDataURL(input.files[i]);
                }
            }
        };
        $('#images').on('change', function () {
            multiImgPreview(this, 'div.imgPreview');
        });
    });
</script>

resources/views/admin/layouts/partials/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="/storage/uploads/images/16x16_black2.png">
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item">
                    <a href="{{route('admin.users.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Users
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.room_categories.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-couch"></i>
                        <p>
                            Room categories
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.designs.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-ruler-combined"></i>
                        <p>
                            Design Projects
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.requests.index')}}" class="nav-link">
                        <i class="nav-icon fas fa-inbox"></i>
                        <p>
                            Consultation requests
                        </p>
                    </a>
                </li>

                <!-- logout -->
                <li class="nav-item">
                    <form id="logout" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                    </form>
                    <a href="#logout" onclick="event.preventDefault();document.getElementById('logout').submit()" class="nav-link">
                        <i class="nav-icon fas fa-sign-out-alt"></i>
                        <p>
                            @lang('app.logout')
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>