routes/web.php
<?php

use App\Http\Controllers\Admin\Designs\ConsultationRequestController;
use App\Http\Controllers\Admin\Designs\DesignController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\RoomCategoryController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.index');
});

Route::prefix('admin')
    ->middleware('auth')
    ->name('admin.')->group(function(){
    Route::get('/', [HomeController::class, 'index']);
    Route::resource('users', UserController::class);
    Route::resource('room_categories', RoomCategoryController::class);
    Route::resource('designs',DesignController::class);
    Route::resource('requests',ConsultationRequestController::class);
    Route::resource('images',ImageController::class);
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Design.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Design extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'year',
        'author',
        'room_category_id',
    ];

    /**
     * @return BelongsTo
     */
    public function roomCategory(): BelongsTo
    {
        return $this->belongsTo(RoomCategory::class);
    }

    /**
     * @return BelongsToMany
     */
    public function images(): BelongsToMany
    {
        return $this->belongsToMany(Image::class);
    }

}

app/Http/Controllers/Admin/Designs/ConsultationRequestController.php
<?php

namespace App\Http\Controllers\Admin\Designs;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateConsultationRequestsRequest;
use App\Models\City;
use App\Models\ConsultationRequest;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ConsultationRequestController extends Controller
{
    /**
     * @return view|Application|Factory
     */
    public function index()
    {
       $requests =  ConsultationRequest::with('roomCategory')->get();
        return view('admin.requests.index', compact('requests'));
    }

    /**
     * @param UpdateConsultationRequestsRequest $request
     * @return RedirectResponse
     */
    public function store(UpdateConsultationRequestsRequest $request): RedirectResponse
    {
        City::all();
        ConsultationRequest::create($request->all());
        return redirect()->to('/#/consultation');
    }

    /**
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id): RedirectResponse
    {
        $consultation_request = ConsultationRequest::find($id);
        $consultation_request->delete();

        return redirect()->route('admin.requests.index');
    }

    /**
     * @param $id
     * @return Application|Factory|View
     */
    public function show($id){
        $model = ConsultationRequest::where('id', $id)->first();
        return view('admin.requests.show', compact('model'));
    }
}

app/Http/Controllers/Admin/Designs/DesignController.php
<?php

namespace App\Http\Controllers\Admin\Designs;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateDesignsRequest;
use App\Models\Design;
use App\Models\Image;
use App\Models\RoomCategory;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;


class DesignController extends Controller
{
    /**
     * @return View
     */
    public function index(): view
    {
        $room_categories = RoomCategory::get();
        $images = Image::get();
        $designs = Design::with('roomCategory', 'images')->get();
        return view('admin.designs.index', compact('designs', 'room_categories', 'images'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return $this->edit(new Design());
    }

    /**
     * @param Design $design
     * @return View
     */
    public function edit(Design $design): View
    {
        $model = $design;
        $room_categories = RoomCategory::get();
        $image = Image::all();
        return view('admin.designs.edit', compact('model', 'room_categories', 'image'));
    }

    /**
     * @param UpdateDesignsRequest $request
     * @return RedirectResponse
     */
    public function store(UpdateDesignsRequest $request): RedirectResponse
    {
        return $this->update($request, new Design());
    }

    /**
     * @param UpdateDesignsRequest $request
     * @param Design $design
     * @return Application|Factory|View|RedirectResponse
     */
    public function update(UpdateDesignsRequest $request, Design $design)
    {
        $design->fill($request->all())->save();
        $imageIds = Image::upload($request);
        $design->images()->sync($imageIds);
        return redirect()->route('admin.designs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View|RedirectResponse
     */
    public function show(int $id)
    {
        $room_categories = RoomCategory::get();
        $design_category = Design::where('room_category_id', $id)->get();

        return view('admin.designs.show', compact('design_category', 'room_categories'));
    }

    /**
     * @param Design $design
     * @return RedirectResponse
     */
    public function destroy(Design $design): RedirectResponse
    {
        $design->images()->delete();
        $design->delete();
        return redirect()->back();
    }
}

resources/views/admin/designs/edit.blade.php
@extends('admin.layouts.page',['content_title'=>''])

@section('content')
    <?php
    if ($model->exists) {
        $action = 'Edit Design';
        $route = route('admin.designs.update', $model);
        $required = '*Showing old images. Required to choose new one.';
    } else {
        $action = 'Create Design';
        $route = route('admin.designs.store');
        $required = '';
    }
    ?>
    <section>
        <div class="container">
            <div class=" text-center mt-5 ">
                <h1>{{$action}}</h1>
            </div>
            <div class="row ">
                <div class="col-lg-7 mx-auto">
                    <div class="card mt-2 mx-auto p-4 bg-light">
                        <div class="card-body bg-light">
                            <div class="container">
                                <form action="{{$route}}" method="POST" enctype="multipart/form-data">
                                    @if($model->exists)
                                        @method('PUT')
                                    @endif
                                    @csrf()
                                    <div class="controls">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="title">Title</label>
                                                    <input id="title" type="text" name="title" class="form-control"
                                                           placeholder="Enter title" value="{{$model->title ?? ''}}">

                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="date">Project year</label>
                                                    <input type="text" name="year"
                                                           class="form-control date-picker" placeholder="Select year"
                                                           autocomplete="off" value="{{$model->year ?? ''}}">

                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group"><label for="author">Author</label>
                                                    <input id="author" type="text" name="author" class="form-control"
                                                           placeholder="Enter author" value="{{$model->author ?? ''}}">

                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group"><label for="form_need">Select room</label>
                                                    <select id="room_categories" name="room_category_id"
                                                            class="form-control">
                                                        <option value="" selected disabled>--Select Room--</option>
                                                        @foreach($room_categories as $room_category)
                                                            <option {{$room_category->id === $model->room_category_id ?
                                                            'selected' : ''}} value="{{$room_category->id}}">
                                                                {{$room_category->title}}
                                                            </option>
                                                        @endforeach
                                                    </select>

                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="description">Description</label>
                                                    <textarea id="description" name="description" class="form-control"
                                                              rows="4">
                                                    {{$model->description ?? ''}}
                                                </textarea>

                                                </div>
                                            </div>
                                        </div>
                                        <div>
                                            <div class="form-group">
                                                <p>{{$required}}</p>
                                                <div class="container d-flex row my-2">
                                                    @foreach($model->images as $image)
                                                        <div class="image_block mr-2">
                                                            <a href="/storage/uploads/images/{{$image->title ?? ''}}">
                                                                <img
                                                                    src="/storage/uploads/images/{{$image->title ?? ''}}"
                                                                    alt="not available" width="100"/>
                                                            </a>
                                                        </div>
                                                    @endforeach
                                                </div>
                                                <div class="custom-file">
                                                    <input type="file" name="imageFile[]" class="custom-file-input"
                                                           id="images" multiple="multiple">

                                                    <label class="custom-file-label" for="images">Choose image</label>
                                                </div>
                                                <div class="user-image mb-3 text-center">
                                                    <div class="imgPreview"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    @if (count($errors) > 0)
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    @if(session()->has('message'))
                                        <div class="alert alert-success">
                                            {{ session()->get('message') }}
                                        </div>
                                    @endif
                                    <div class="row mt-3">
                                        <button type="submit" class="btn btn-primary mx-auto">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/designs/index.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.designs')])

@section('content')

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div>
                                <a href="{{route('admin.designs.create')}}" class="btn btn-primary float-left">Create
                                    new design</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div id="room_categories_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="container">
                                        <ul class="list-group">
                                            <li class="list-group-item active">Choose room category</li>
                                            @foreach($room_categories as $room_category)
                                                <li class="list-group-item">
                                                    <a href="{{url('admin/designs/'.$room_category->id)}}">
                                                        {{$room_category->title ?? ''}}
                                                    </a>
                                                </li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/admin/designs/show.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.designs')])

@section('content')
    <div class="card-body">
        <div id="designs" class="dataTables_wrapper dt-bootstrap4">
            <div class="row">
                <div class="col-sm-12">
                    <table id="designs"
                           class="table table-bordered table-hover dataTable dtr-inline"
                           role="grid" aria-describedby="example2_info" style="table-layout:fixed;">
                        <thead class="thead-light">
                        <tr role="row">
                            <th class="sorting sorting_asc col-1" tabindex="0" rowspan="1" colspan="1"
                                aria-sort="ascending">
                                No.
                            </th>
                            <th class="sorting col-1" rowspan="1" colspan="1">
                                Room category
                            </th>
                            <th class="sorting col-2" rowspan="1" colspan="">
                                Title
                            </th>
                            <th class="sorting col-4" rowspan="1" colspan="">
                                Description
                            </th>

                            <th class="sorting col-1" rowspan="1" colspan="">
                                Year
                            </th>
                            <th class="sorting col-1" rowspan="1" colspan="">
                                Author
                            </th>
                            <th class="sorting col-2" rowspan="1" colspan="">
                                Images
                            </th>

                            <th class="sorting col-1" rowspan="1" colspan="1">
                                Actions
                            </th>
                        </tr>
                        </thead>
                        <tbody cellpadding="0">
                        @foreach($design_category as $design)
                            <tr class="odd">
                                <td>{{$design->roomCategory->title ?? ''}}</td>
                                <td>{{$design->title ?? ''}}</td>
                                <td style="word-wrap: break-word;">{{$design->description ?? ''}}</td>
                                <td>{{$design->year ?? ''}}</td>
                                <td>{{$design->author ?? ''}}</td>
                                <td>
                                    @foreach($design->images as $image)
                                        <a href="/storage/uploads/images/{{$image->title ?? ''}}" class="table_image_link">
                                            <img src="/storage/uploads/images/{{$image->title ?? ''}}" alt="not available" width="80"/>
                                        </a>
                                    @endforeach
                                </td>
                                <td>
                                    <div class=" mx-auto">
                                        <a class="btn btn-actions mb-2"
                                           href="{{route('admin.designs.edit', $design->id)}}">Edit</a>
                                        <form action="{{route('admin.designs.destroy', $design->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <input type="submit" class="btn btn-actions" value='Delete'>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection