routes/web.php
<?php

use App\Http\Controllers\Admin\Designs\ConsultationRequestController;
use App\Http\Controllers\Admin\Designs\DesignController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\RoomCategoryController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.index');
});

Route::prefix('admin')
    ->middleware('auth')
    ->name('admin.')->group(function(){
    Route::get('/', [HomeController::class, 'index']);
    Route::resource('users', UserController::class);
    Route::resource('room_categories', RoomCategoryController::class);
    Route::resource('designs',DesignController::class);
    Route::resource('requests',ConsultationRequestController::class);
    Route::resource('images',ImageController::class);
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;


/**
 * App\Models\User
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $phone
 * @property string $address
 * @property Carbon|null $email_verified_at
 * @property string $password
 * @property string|null $remember_token
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 * @property-read DatabaseNotificationCollection|DatabaseNotification[] $notifications
 * @property-read int|null $notifications_count
 * @method static UserFactory factory(...$parameters)
 * @method static \Illuminate\Database\Eloquent\Builder|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|User newQuery()
 * @method static Builder|User onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|User query()
 * @method static \Illuminate\Database\Eloquent\Builder|User whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereFirstName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereLastName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User wherePhone($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder|User whereUpdatedAt($value)
 * @method static Builder|User withTrashed()
 * @method static Builder|User withoutTrashed()
 * @mixin Eloquent
 */
class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'phone',
        'address',
        'password',
    ];

    /**
     * Hash password
     * @param $input
     */
    public function setPasswordAttribute($input)
    {
        if ($input)
            $this->attributes['password'] = app('hash')->needsRehash($input) ? Hash::make($input) : $input;
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateUsersRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class UserController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $users = User::get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return $this->edit(new User());
    }

    /**
     * @param User $user
     * @return View
     */
    public function edit(User $user): View
    {
        $model = $user;
        return view('admin.users.edit', compact('model'));
    }

    /**
     * @param UpdateUsersRequest $request
     * @return View
     */
    public function store(UpdateUsersRequest $request): View
    {
        return $this->update($request, new User());
    }

    /**
     * @param UpdateUsersRequest $request
     * @param User $user
     * @return View
     */
    public function update(UpdateUsersRequest $request, User $user): View
    {
        $user->fill($request->all())->save();
        return $this->index();
    }

    /**
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id): RedirectResponse
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('admin.users.index');
    }

}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.users')])

@section('content')
    <?php
    if($model->exists){
        $action = 'Edit User';
        $route = route('admin.users.update',$model);
    }else{
        $action = 'Create User';
        $route = route('admin.users.store');
    }
    ?>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{$action}}</h3>
                        </div>

                        <form action="{{$route}}" method="POST">
                            @if($model->exists)
                                @method('PUT')
                            @endif
                            @csrf()
                            <div class="card-body row">
                                <div class="form-group col-4">
                                    <label for="first_name">First name</label>
                                    <input type="text" class="form-control" name="first_name" id="first_name" value= "{{$model->first_name ?? ''}}" placeholder="First name">
                                </div>

                                <div class="form-group col-4">
                                    <label for="last_name">Last name</label>
                                    <input type="text" class="form-control" name="last_name" id="last_name" value= "{{$model->last_name ?? ''}}" placeholder="Last name">
                                </div>

                                <div class="form-group col-4">
                                    <label for="email">Email</label>
                                    <input type="email" class="form-control" name="email" id="email" value= "{{$model->email ?? ''}}" placeholder="Email">
                                </div>

                                <div class="form-group col-4">
                                    <label for="phone">Phone</label>
                                    <input type="text" class="form-control" name="phone" id="phone" value= "{{$model->phone ?? ''}}" placeholder="Phone">
                                </div>

                                <div class="form-group col-4">
                                    <label for="address">Address</label>
                                    <input type="text" class="form-control" name="address" id="address" value= "{{$model->address ?? ''}}" placeholder="Address">
                                </div>

                                <div class="form-group col-4">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control" name="password" id="password" value= "{{$model->password ?? ''}}" placeholder="Password">
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.users')])

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div>
                                <a href="{{route('admin.users.create')}}" class="btn btn-primary float-left">Add new user</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div id="user_table_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="user_table"
                                               class="table table-bordered table-hover dataTable dtr-inline"
                                               role="grid" aria-describedby="example2_info">
                                            <thead class="thead-light">
                                            <tr role="row">
                                                <th class="sorting sorting_asc" tabindex="0" rowspan="1" colspan="1"
                                                    aria-sort="ascending">
                                                    No.
                                                </th>
                                                <th class="sorting" rowspan="1" colspan="1">
                                                    First name
                                                </th>
                                                <th class="sorting" rowspan="1" colspan="1">
                                                    Last name
                                                </th>
                                                <th class="sorting" rowspan="1" colspan="1">
                                                    Email
                                                </th>
                                                <th class="sorting" rowspan="1" colspan="1">
                                                    Phone
                                                </th>
                                                <th class="sorting" rowspan="1" colspan="1">
                                                    Address
                                                </th>
                                                <th class="sorting sorting_asc" rowspan="1" colspan="1"
                                                    aria-sort="ascending">
                                                    Created at
                                                </th>
                                                <th class="sorting" rowspan="1" colspan="1">
                                                    Actions
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody cellpadding="0">
                                            @foreach($users as $user)
                                                <tr class="odd">
                                                    <td>{{$user->first_name ?? ''}}</td>
                                                    <td>{{$user->last_name ?? ''}}</td>
                                                    <td>{{$user->email ?? ''}}</td>
                                                    <td>{{$user->phone ?? ''}}</td>
                                                    <td>{{$user->address ?? ''}}</td>
                                                    <td>{{$user->created_at ?? ''}}</td>
                                                    <td>
                                                        <div class="row mx-auto">
                                                        <a class="btn btn-actions px-3"
                                                           href="{{route('admin.users.edit', $user->id)}}">Edit</a>
                                                        <form action="{{route('admin.users.destroy', $user->id)}}" method="post">
                                                            @csrf
                                                            @method('DELETE')
                                                            <input type="submit" class="btn btn-actions mx-3" value='Delete'>
                                                        </form>
                                                        </div>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection