routes/web.php
<?php

use App\Http\Controllers\Admin\Designs\ConsultationRequestController;
use App\Http\Controllers\Admin\Designs\DesignController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\RoomCategoryController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.index');
});

Route::prefix('admin')
    ->middleware('auth')
    ->name('admin.')->group(function(){
    Route::get('/', [HomeController::class, 'index']);
    Route::resource('users', UserController::class);
    Route::resource('room_categories', RoomCategoryController::class);
    Route::resource('designs',DesignController::class);
    Route::resource('requests',ConsultationRequestController::class);
    Route::resource('images',ImageController::class);
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/RoomCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class RoomCategory extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
    ];

}

app/Http/Controllers/Admin/RoomCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateRoomCategoriesRequest;
use App\Models\RoomCategory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class RoomCategoryController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $room_categories = RoomCategory::get();
        return view('admin.room_categories.index', compact('room_categories'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return $this->edit(new RoomCategory());
    }

    /**
     * @param RoomCategory $roomCategory
     * @return View
     */
    public function edit(RoomCategory $roomCategory): View
    {
        $model = $roomCategory;
        return view('admin.room_categories.edit', compact('model'));
    }

    /**
     * @param UpdateRoomCategoriesRequest $request
     * @return RedirectResponse
     */
    public function store(UpdateRoomCategoriesRequest $request): RedirectResponse
    {
        return $this->update($request, new RoomCategory());
    }

    /**
     * @param UpdateRoomCategoriesRequest $request
     * @param RoomCategory $roomCategory
     * @return RedirectResponse
     */
    public function update(UpdateRoomCategoriesRequest $request, RoomCategory $roomCategory): RedirectResponse
    {
        $roomCategory->fill($request->all())->save();
        return redirect()->route('admin.room_categories.index');
    }

    /**
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id): RedirectResponse
    {
        $room_category = RoomCategory::find($id);
        $room_category->delete();

        return redirect()->route('admin.room_categories.index');
    }

}

resources/views/admin/room_categories/edit.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.room_categories')])

@section('content')
    <?php
    if($model->exists){
        $action = 'Edit Room';
        $route = route('admin.room_categories.update',$model);
    }else{
        $action = 'Create room';
        $route = route('admin.room_categories.store');
    }
    ?>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">{{$action}}</h3>
                        </div>

                        <form action="{{$route}}" method="POST">
                            @if($model->exists)
                                @method('PUT')
                            @endif
                            @csrf()
                            <div class="card-body row">
                                <div class="form-group col-4">
                                    <label for="title">Room name</label>
                                    <input type="text" class="form-control" name="title" id="title" value= "{{$model->title ?? ''}}" placeholder="Title">
                                    <div class="alert-danger">{{ $errors->first('title') }}</div>
                                </div>

                                <div class="form-group col-8">
                                    <label for="description">Description</label>
                                    <textarea class="form-control" name="description" id="description" rows="5" placeholder="Description">{{$model->description ?? ''}}</textarea>
                                    <div class="alert-danger">{{ $errors->first('description') }}</div>

                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/room_categories/index.blade.php
@extends('admin.layouts.page',['content_title'=>trans('app.room_categories')])

@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div>
                                <a href="{{route('admin.room_categories.create')}}" class="btn btn-primary float-left">Create new room category</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div id="room_categories_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table id="room_categories_table"
                                               class="table table-bordered table-hover dataTable dtr-inline"
                                               role="grid" aria-describedby="example2_info">
                                            <thead class="thead-light">
                                            <tr role="row">
                                                <th class="sorting sorting_asc col-1" tabindex="0" rowspan="1" colspan="1"
                                                    aria-sort="ascending">
                                                    No.
                                                </th>
                                                <th class="sorting col-3" rowspan="1" colspan="1">
                                                    Room name
                                                </th>
                                                <th class="sorting col-6" rowspan="1" colspan="">
                                                    Description
                                                </th>
                                                <th class="sorting col-2" rowspan="1" colspan="1">
                                                    Actions
                                                </th>
                                            </tr>
                                            </thead>
                                            <tbody cellpadding="0">
                                            @foreach($room_categories as $room_category)
                                                <tr class="odd">
                                                    <td>{{$room_category->title ?? ''}}</td>
                                                    <td>{{$room_category->description ?? ''}}</td>
                                                    <td>
                                                        <div class="row mx-auto">
                                                            <a class="btn btn-actions px-3"
                                                               href="{{route('admin.room_categories.edit', $room_category->id)}}">Edit</a>
                                                            <form action="{{route('admin.room_categories.destroy', $room_category->id)}}" method="POST">
                                                                @csrf
                                                                @method('DELETE')
                                                                <input type="submit" class="btn btn-actions mx-3" value='Delete'>
                                                            </form>
                                                        </div>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection